services:
    _defaults:
        autowire: true
        autoconfigure: true

    OAuth2\ServerBundle\:
        resource: '../../../src'
        exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php,Command}'

    OAuth2\ServerBundle\Controller\:
        resource: '../../../src/Controller'
        tags: [ 'controller.service_arguments' ]

    OAuth2\GrantType\ClientCredentials: '@oauth2.grant_type.client_credentials'
    OAuth2\Server: '@oauth2.server'
    OAuth2\GrantType\AuthorizationCode: '@oauth2.grant_type.authorization_code'
    OAuth2\GrantType\RefreshToken: '@oauth2.grant_type.refresh_token'
    OAuth2\GrantType\UserCredentials: '@oauth2.grant_type.user_credentials'
    OAuth2\HttpFoundationBridge\Request: '@oauth2.request'
    OAuth2\HttpFoundationBridge\Response: '@oauth2.response'
    Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'