services:
    _defaults:
        autowire: true
        autoconfigure: true

    OAuth2\ServerBundle\:
        resource: '../../../src'
        exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php,Command}'

    OAuth2\ServerBundle\Controller\:
        resource: '../../../src/Controller'
        tags: [ 'controller.service_arguments' ]

    OAuth2\ServerBundle\Controller\TokenController:
        class: OAuth2\ServerBundle\Controller\TokenController
        arguments:
            - '@oauth2.server'
            - '@oauth2.grant_type.client_credentials'
            - '@oauth2.grant_type.authorization_code'
            - '@oauth2.grant_type.refresh_token'
            - '@oauth2.grant_type.user_credentials'
            - '@oauth2.request'
            - '@oauth2.response'