services:
    _defaults:
        autowire: true
        autoconfigure: true

    OAuth2\ServerBundle\:
        resource: '../../../src'
        exclude: '../../../src/{DependencyInjection,Entity,Tests,Kernel.php,Command}'

    OAuth2\ServerBundle\Controller\:
        resource: '../../../src/Controller'
        tags: [ 'controller.service_arguments' ]
